# Generated by Django 6.0.7 on 2026-07-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='region_code',
        ),
        migrations.AlterField(
            model_name='member',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chapters.barangay'),
        ),
        migrations.AlterField(
            model_name='member',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chapters.municipality'),
        ),
        migrations.AlterField(
            model_name='member',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chapters.province'),
        ),
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chapters.region'),
        ),
    ]
